#ifndef RESOURCE_H
#define RESOURCE_H

#define IDS_APP_NAME_VER 2
#define IDS_SHELL_VERB 4
#define IDS_SENDTO 6
#define IDS_LOAD_STAT 8
#define IDS_WORK_CANCELLING 10
#define IDS_WORK_SUBTITLE 12
#define IDS_WORK_CACHE 14
#define IDS_WORK_FONT 16
#define IDS_WORK_LOAD 18
#define IDS_WORK_UNLOAD 20
#define IDS_WORK_DONE 22
#define IDS_LICENSE 24
#define IDS_HELP 26
#define IDS_USAGE 28
#define IDS_MANAGE_SHORTCUT 30
#define IDS_SHORTCUT_ERROR_ADD 32
#define IDS_SHORTCUT_ERROR_DEL 34
#define IDS_SHORTCUT_ADD_DIR_BG 36
#define IDS_SHORTCUT_DEL_DIR_BG 38
#define IDS_SHORTCUT_ADD_SENDTO 40
#define IDS_SHORTCUT_DEL_SENDTO 42

#endif
