#ifndef RESOURCE_H
#define RESOURCE_H

#ifndef FONTLOADERSUB_GIT_VERSION
#define FONTLOADERSUB_GIT_VERSION "ver.unknown"
#endif

#define IDS_APP_NAME_VER 2
#define IDS_SHELL_VERB 4
#define IDS_SENDTO 6
#define IDS_LOAD_STAT 8
#define IDS_WORK_CANCELLING 10
#define IDS_WORK_SUBTITLE 12
#define IDS_WORK_CACHE 14
#define IDS_WORK_FONT 16
#define IDS_WORK_LOAD 18
#define IDS_WORK_UNLOAD 20
#define IDS_WORK_DONE 22
#define IDS_HELP 24
#define IDS_USAGE 26
#define IDS_MANAGE_SHORTCUT 28
#define IDS_SHORTCUT_ERROR_ADD 30
#define IDS_SHORTCUT_ERROR_DEL 32
#define IDS_SHORTCUT_ADD_DIR_BG 34
#define IDS_SHORTCUT_DEL_DIR_BG 36
#define IDS_SHORTCUT_ADD_SENDTO 38
#define IDS_SHORTCUT_DEL_SENDTO 40
#define IDS_MENU 42

// control id
#define ID_BTN_MENU 101
#define ID_BTN_RESCAN 102
#define ID_BTN_EXPORT 103
#define ID_BTN_HELP 104

// menu
#define IDR_BTN_MENU 1

#endif
